# Generated by Django 3.0.6 on 2020-06-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterID', models.CharField(max_length=200, verbose_name='EID')),
                ('DTE', models.CharField(max_length=200, verbose_name='DTE')),
                ('email', models.CharField(max_length=200, verbose_name='EMAIL')),
            ],
        ),
    ]
