# Generated by Django 3.0.6 on 2020-06-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
